[wokwi]
version = 1
firmware = 'C:/Users/TRETEC/OneDrive/سطح المكتب/TP USTHB/dishack.hex'
elf = 'C:/Users/TRETEC/OneDrive/سطح المكتب/TP USTHB/dishack.elf'

# Forward http://localhost:8180 to port 80 on the simulated ESP32:
[[net.forward]]
from = "localhost:8180"
to = "target:80"\\\\\\\\\\\\\\